#! /bin/sh

sxhkd &

bspc monitor 0x00400004 -n "1" -d 1/{a,b,c,d,e,f}
bspc monitor 0x00400006 -n "2" -d 2/{a,b,c,d,e,f}
bspc monitor 0x00400008 -n "3" -d 3/{a,b,c,d,e,f}
bspc monitor 0x00400002 -n "4" -d 4/{a,b,c,d,e,f,g}

bspc config border_width         2
bspc config border_width                  2
bspc config normal_border_color           "#073642"
bspc config focused_border_color          "#859900"
bspc config window_gap                    12
# bspc config top_padding                   18
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config external_rules_command "/home/kyle/bin/spotifyRules";
bspc config pointer_motion_interval 7ms

# bspc wa -a Full 5760x1080+0+1440
# bspc node somenode -m Full -t fullscreen
bspc rule -a "TeamSpeak 3" desktop='1/a'
bspc rule -a "Hexchat" desktop='1/b'
bspc rule -a "discord" desktop='1/c'
bspc rule -a "Spotify" desktop='2/a'
bspc rule -a "Zeal" desktop='2/b'
bspc rule -a "Mailspring" desktop='2/c'
bspc rule -a "Slack" desktop='1/e'
bspc rule -a "Code" desktop='4/c'

polybar full &
dunst &
dropbox &
~/bin/osuCopy &
xset dpms 0 0 0 &
xset s off -dpms &
xsetroot -cursor_name left_ptr &
~/bin/enableBridge &
~/bin/rmXsession &
~/bin/startVM &
~/bin/disableKeypad.sh &
~/bin/setPad.sh &
~/.screenlayout/monitors.sh &
plex-mpv-shim &
synergy &
scream-pulse -i br0 &
rm ~/.toggleWindows &
sh -c 'sleep 6; exec teamspeak3' &
mailspring &
hexchat &
code &
# env HOME=/home/kyle/spotify_fix_zeus spotify &
mpd &
bspc desktop -f "2/a"; urxvt -e ncmpcpp &  
~/bin/discordNoCrash.sh &
env QT_STYLE_OVERRIDE=gtk2 zeal &
corectrl &
glava -r "setgeometry 0 1121 2560 1440" &
feh --bg-scale --no-xinerama ~/Pictures/LinuxOnWin.png &
