config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_vim:
    src: vim
    dst: ~/.vim
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  f_synergy.conf:
    src: synergy.conf
    dst: ~/synergy.conf
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_zsh:
    src: zsh
    dst: ~/.zsh
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  d_oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.oh-my-zsh
  f_profile:
    src: profile
    dst: ~/.profile
  d_bin:
    src: bin
    dst: ~/bin
  f_dircolors:
    src: dircolors
    dst: ~/.dircolors
  d_screenlayout:
    src: screenlayout
    dst: ~/.screenlayout
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_glava:
    src: config/glava
    dst: ~/.config/glava
  d_synergy:
    src: config/Synergy
    dst: ~/.config/Synergy
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  d_icons:
    src: icons
    dst: ~/.icons
  f_config:
    src: ssh/config
    dst: ~/.ssh/config
profiles:
  zeus:
    dotfiles:
    - f_vimrc
    - d_vim
    - d_polybar
    - d_bspwm
    - d_sxhkd
    - f_synergy.conf
    - f_xresources
    - f_zshrc
    - d_zsh
    - f_p10k.zsh
    - d_oh-my-zsh
    - f_profile
    - d_bin
    - f_dircolors
    - d_screenlayout
    - d_dunst
    - d_glava
    - d_synergy
    - d_gtk-3.0
    - d_icons
    - f_config
